name: Code Formatting Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check code formatting with Prettier
      run: npm run format:check
      
    - name: Comment on PR if formatting issues found
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ **Code formatting issues detected!**\n\nPlease run `npm run format` locally to fix formatting issues, then commit and push the changes.\n\n```bash\nnpm run format\ngit add .\ngit commit -m "Fix code formatting"\ngit push\n```'
          })
          
    - name: Fail if formatting issues found
      if: failure()
      run: |
        echo "❌ Code formatting issues detected!"
        echo "Run 'npm run format' locally to fix them."
        exit 1
