name: Package on Release

on:
  release:
    types: [published]

jobs:
  package-mac:
    # Notarization is taking too long, exit
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          
      - name: npm install
        run: |
          npm install

      - name: Create dummy .env for CI build
        run: |
          echo "# Dummy .env file for CI build" > .env
          echo "NODE_ENV=production" >> .env
          echo "CI=true" >> .env

      - name: Debug environment variables
        run: |
          echo "CSC_LINK length: ${#CSC_LINK}"
          echo "CSC_KEY_PASSWORD set: $([[ -n "$CSC_KEY_PASSWORD" ]] && echo "yes" || echo "no")"
          echo "APPLE_ID set: $([[ -n "$APPLE_ID" ]] && echo "yes" || echo "no")"
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}

      - name: Package and Upload to S3
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          npm run package:publish

  package-windows:
    timeout-minutes: 30
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: npm install
        run: |
          npm install

      - name: Create dummy .env for CI build
        run: |
          echo "# Dummy .env file for CI build" > .env
          echo "NODE_ENV=production" >> .env
          echo "CI=true" >> .env

      - name: Package and Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          npm run package:publish               