name: PR Checks

on:
  pull_request:
    branches: [main, develop]

jobs:
  quick-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run formatting check and unit tests in parallel
        run: |
          npm run format:check &
          npm run test:run &
          wait

      - name: Comment on PR if checks failed
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **PR checks failed!**\n\nPlease fix the issues and push again:\n\n- Run `npm run format` to fix formatting\n- Run `npm test` to check unit tests\n\n```bash\nnpm run format\nnpm test\ngit add .\ngit commit -m "Fix PR checks"\ngit push\n```'
            })
